name: Helm Chart CI (Core)
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-core.yml'
      - '.github/workflows/core-verification-job-template.yml'
      - 'keda/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci-core.yml'
      - '.github/workflows/core-verification-job-template.yml'
      - 'keda/**'

jobs:
  lint-helm-3-x:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Helm install
      uses: Azure/setup-helm@v1

    - name: Lint 'KEDA' Helm chart
      run: helm lint keda

  azure-workload-identity:
    uses: ./.github/workflows/core-verification-job-template.yml    
    needs: lint-helm-3-x
    with:
      enableAzureWorkloadIdentity: "[false, true]"
      azureTenantId: "contoso"
      azureClientId: "ABC"

  pod-disruption-budget:
    uses: ./.github/workflows/core-verification-job-template.yml    
    needs: lint-helm-3-x
    with:
      enablePodDisruptionBudget: "[false, true]"
