on:
  workflow_call:
    inputs:
      jobNameTemplate:
        description: 'Template of name to use for jobs'
        required: false
        default: 'Deploy to Kubernetes ${{ matrix.kubernetesVersion }} (${{ (matrix.enableAzureWorkloadIdentity == true && ''With Azure Workload Identity'') || ''Without Azure Workload Identity'' }})'
        type: string
      enableAzureWorkloadIdentity:
        description: 'Stringified JSON array listing configuration options for Azure Workload Identity'
        required: false
        default: '[\"false\"]'
        type: string
      azureTenantId:
        description: 'Id of Azure tenant to use for Azure Workload Identity'
        required: false
        type: string
      azureClientId:
        description: 'Id of Azure tenant to use for Azure Workload Identity'
        required: false
        type: string
jobs:
  verify-chart:
    name: Deploy to Kubernetes ${{ matrix.kubernetesVersion }} (${{ (matrix.enableAzureWorkloadIdentity == true && 'With Azure Workload Identity') || 'Without Azure Workload Identity' }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Workaround, see https://github.community/t/reusable-workflow-with-strategy-matrix/205676
        enableAzureWorkloadIdentity: ${{ fromJson(inputs.enableAzureWorkloadIdentity) }}
        kubernetesVersion: [v1.23, v1.22, v1.21, v1.20, v1.19, v1.18, v1.17]
        include:
          # Azure Workload Identity
        - enableAzureWorkloadIdentity: true
          tenantId: ${{ inputs.azureTenantId }}
          clientId: ${{ inputs.azureClientId }}
        - enableAzureWorkloadIdentity: false
          tenantId: ""
          clientId: ""
          # Images are defined on every Kind release
          # See https://github.com/kubernetes-sigs/kind/releases
        - kubernetesVersion: v1.23
          kindImage: kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
        - kubernetesVersion: v1.22
          kindImage: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
        - kubernetesVersion: v1.21
          kindImage: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
        - kubernetesVersion: v1.20
          kindImage: kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9
        - kubernetesVersion: v1.19
          kindImage: kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729
        - kubernetesVersion: v1.18
          kindImage: kindest/node:v1.18.19@sha256:7af1492e19b3192a79f606e43c35fb741e520d195f96399284515f077b3b622c
        - kubernetesVersion: v1.17
          kindImage: kindest/node:v1.17.17@sha256:66f1d0d91a88b8a001811e2f1054af60eef3b669a9a74f9b6db871f2f1eeed00
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Helm install
      uses: Azure/setup-helm@v1
      
    - name: Create k8s ${{ matrix.kubernetesVersion }} Kind Cluster
      uses: helm/kind-action@v1.2.0
      with:
        node_image: ${{ matrix.kindImage }}

    - name: Show Kubernetes version
      run: |
        kubectl version

    - name: Show Kubernetes nodes
      run: |
        kubectl get nodes -o wide

    - name: Show Helm version
      run: |
        helm version

    - name: Create KEDA namespace
      run: kubectl create ns keda

    - name: Template Helm chart
      run: helm template keda ./keda/ --namespace keda --set podIdentity.azureWorkload.enabled=${{ matrix.enableAzureWorkloadIdentity }} --set podIdentity.azureWorkload.tenantId=${{ matrix.tenantId }} --set podIdentity.azureWorkload.clientId=${{ matrix.clientId }}

    - name: Install Helm chart
      run: helm install keda ./keda/ --namespace keda --set podIdentity.azureWorkload.enabled=${{ matrix.enableAzureWorkloadIdentity }} --set podIdentity.azureWorkload.tenantId=${{ matrix.tenantId }} --set podIdentity.azureWorkload.clientId=${{ matrix.clientId }}

    - name: Show Kubernetes resources
      run: kubectl get all --namespace keda
      if: always()

    - name: Get all CRDs
      run: kubectl get crds -o wide

    - name: Verify clustertriggerauthentications.keda.sh CRD is installed
      run: kubectl get crd/clustertriggerauthentications.keda.sh -o wide

    - name: Verify triggerauthentications.keda.sh CRD is installed
      run: kubectl get crd/triggerauthentications.keda.sh -o wide

    - name: Verify scaledjobs.keda.sh CRD is installed
      run: kubectl get crd/scaledjobs.keda.sh -o wide

    - name: Verify scaledobjects.keda.sh CRD is installed
      run: kubectl get crd/scaledobjects.keda.sh -o wide

    - name: Get all ScaledObjects
      run: kubectl get scaledobjects -o wide

    - name: Get all ScaledJobs
      run: kubectl get scaledjobs -o wide

    - name: Get all TriggerAuthentication
      run: kubectl get triggerauth -o wide

    - name: Get all ClusterTriggerAuthentication
      run: kubectl get clustertriggerauth -o wide

    - name: Deploy Nginx with autoscaling
      run: kubectl apply -f ./samples/nginx-scaledobject.yml

    - name: Get our Nginx ScaledObject
      run: kubectl get scaledobjects/nginx-autoscaling -o wide
      if: always()